import { describe, it, expect } from 'vitest';
import { createAITagger , projectAttribution } from './ai-tags.js';

describe('AI Tagging', () => {
  const tagger = createAITagger();

  describe('explicit level', () => {
    it('should classify trailers as explicit', () => {
      const cases = [
        'feat: new feature\n\nAI: true',
        'feat: new feature\n\nX-AI: true',
        'feat: new feature\n\nCo-authored-by: Claude <noreply@anthropic.com>',
        'feat: new feature\n\nCo-authored-by: copilot[bot] <copilot@github.com>',
        'feat: new feature\n\nCo-authored-by: ChatGPT <noreply@openai.com>',
      ];

      cases.forEach((message) => {
        const result = tagger(message);
        expect(result.attribution).toBe('ai');
        expect(result.level).toBe('explicit');
      });
    });

    it('should classify [AI] tag as explicit', () => {
      const result = tagger('[AI] automated code generation');
      expect(result.attribution).toBe('ai');
      expect(result.level).toBe('explicit');
      expect(result.sources).toContain('tag:[ai]');
    });

    it('should classify creation verb + tool as explicit', () => {
      const cases = [
        'feat: generated by copilot',
        'feat: created with claude',
        'feat: written using chatgpt',
        'feat: built with gemini',
        'feat: cursor generated the auth module',
      ];

      cases.forEach((message) => {
        const result = tagger(message);
        expect(result.attribution).toBe('ai');
        expect(result.level).toBe('explicit');
      });
    });

    it('should classify Claude Code commits as explicit', () => {
      const claudeCommit = `fix: resolve authentication bug

Generated with Claude Code
Co-Authored-By: Claude <noreply@anthropic.com>`;

      const result = tagger(claudeCommit);
      expect(result.attribution).toBe('ai');
      expect(result.level).toBe('explicit');
    });
  });

  describe('implicit level', () => {
    it('should classify suggestion/help verbs + tool as implicit', () => {
      const cases = [
        'fix: copilot suggestions',
        'feat: chatgpt assisted refactoring',
        'feat: with help from claude',
        'fix: reviewed by gemini',
      ];

      cases.forEach((message) => {
        const result = tagger(message);
        expect(result.attribution).toBe('ai');
        expect(result.level).toBe('implicit');
      });
    });
  });

  describe('mention level', () => {
    it('should classify negative context + tool as mention (ai: false)', () => {
      const cases = [
        'fix: copilot bug in autocomplete',
        'chore: add cursor support',
        'chore: configure windsurf settings',
        'chore: update claude integration',
        'docs: document copilot setup',
      ];

      cases.forEach((message) => {
        const result = tagger(message);
        expect(result.attribution).not.toBe('ai');
        expect(result.level).toBe('mention');
      });
    });

    it('should classify bare tool name as mention (ai: false)', () => {
      const cases = [
        'feat: copilot improvements',
        'chore: cursor config changes',
      ];

      cases.forEach((message) => {
        const result = tagger(message);
        expect(result.attribution).not.toBe('ai');
        expect(result.level).toBe('mention');
      });
    });
  });

  describe('none level', () => {
    it('should classify messages without AI references as none', () => {
      const cases = [
        'regular commit message',
        'feat: add user authentication',
        'fix: resolve memory leak in parser',
        'chore: add AI attribution manifest',
      ];

      cases.forEach((message) => {
        const result = tagger(message);
        expect(result.attribution).not.toBe('ai');
        expect(result.level).toBe('none');
      });
    });
  });

  describe('edge cases', () => {
    it('should not match human Co-authored-by', () => {
      const result = tagger('feat: new feature\n\nCo-authored-by: John <john@example.com>');
      expect(result.attribution).not.toBe('ai');
      expect(result.level).toBe('none');
    });

    it('should handle custom patterns as explicit', () => {
      const customTagger = createAITagger({ patterns: ['custom-ai-tool'] });
      const result = customTagger('fix: custom-ai-tool generated code');
      expect(result.attribution).toBe('ai');
      expect(result.level).toBe('explicit');
    });

    it('should prioritize explicit over mention context', () => {
      const result = tagger('fix: generated with claude');
      expect(result.attribution).toBe('ai');
      expect(result.level).toBe('explicit');
    });
  });

  describe('bot blocklist', () => {
    it('should not classify non-AI bot trailers as AI', () => {
      const cases = [
        'chore(deps): bump lodash\n\nCo-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>',
        'chore(deps): update deps\n\nCo-authored-by: renovate[bot] <renovate@whitesourcesoftware.com>',
        'ci: retry\n\nCo-authored-by: github-actions[bot] <github-actions[bot]@users.noreply.github.com>',
      ];

      cases.forEach((message) => {
        const result = tagger(message);
        expect(result.attribution).not.toBe('ai');
        expect(result.level).toBe('none');
      });
    });

    it('should still classify AI bot trailers as explicit', () => {
      const result = tagger(
        'feat: new feature\n\nCo-authored-by: copilot[bot] <copilot@github.com>'
      );
      expect(result.attribution).toBe('ai');
      expect(result.level).toBe('explicit');
    });

    it('should support extending the blocklist via config', () => {
      const customTagger = createAITagger({ patterns: [], botBlocklist: ['acme-bot'] });
      const result = customTagger(
        'chore: automated\n\nCo-authored-by: acme-bot <bot@github.com>'
      );
      expect(result.attribution).not.toBe('ai');
      expect(result.level).toBe('none');
    });

    it('should still detect a real AI co-author alongside a blocklisted bot', () => {
      const result = tagger(
        `feat: thing

Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Co-authored-by: Claude <noreply@anthropic.com>`
      );
      expect(result.attribution).toBe('ai');
      expect(result.level).toBe('explicit');
    });
  });

  describe('configurable tools', () => {
    it('should detect custom tool names across all levels', () => {
      const customTagger = createAITagger({ patterns: [], tools: ['devbot'] });

      expect(customTagger('feat: generated by devbot').level).toBe('explicit');
      expect(customTagger('feat: devbot suggestions').level).toBe('implicit');
      expect(customTagger('fix: devbot bug').level).toBe('mention');
      expect(customTagger('feat: devbot improvements').level).toBe('mention');
      expect(customTagger('regular commit').level).toBe('none');
    });

    it('should still detect default tools when custom tools are added', () => {
      const customTagger = createAITagger({ patterns: [], tools: ['devbot'] });

      expect(customTagger('feat: generated by copilot').level).toBe('explicit');
      expect(customTagger('feat: copilot suggestions').level).toBe('implicit');
    });

    it('should detect custom trailer domains', () => {
      const customTagger = createAITagger({ patterns: [], trailerDomains: ['mycompany.com'] });

      const result = customTagger('feat: new feature\n\nCo-authored-by: Bot <bot@mycompany.com>');
      expect(result.attribution).toBe('ai');
      expect(result.level).toBe('explicit');
    });

    it('treats configured tool names as literals, not regex programs', () => {
      const customTagger = createAITagger({ patterns: [], tools: ['dev.bot'] });

      expect(customTagger('generated by dev.bot').attribution).toBe('ai');
      expect(customTagger('generated by devXbottt').attribution).toBe('unknown');
    });

    it('rejects an invalid custom regex with an actionable error', () => {
      expect(() => createAITagger({ patterns: ['['], tools: [] })).toThrow(
        'Invalid AI detection regex "["'
      );
    });
  });

  describe('autonomy mode inference', () => {
    it('infers agent from Claude Code and the Claude trailer convention', () => {
      const result = tagger(
        'fix: bug\n\nGenerated with Claude Code\nCo-Authored-By: Claude <noreply@anthropic.com>'
      );
      expect(result.mode).toBe('agent');
      expect(result.evidence).toBe('inferred');
    });

    it('does not infer autonomy from ambiguous tool names', () => {
      expect(tagger('feat: generated by copilot').mode).toBe('unknown');
      expect(tagger('feat: generated by cursor').mode).toBe('unknown');
      expect(tagger('feat: written using chatgpt').mode).toBe('unknown');
    });

    // The two axes exist precisely for this state: we concluded AI
    // participated, we cannot say at what level. The old single-axis model
    // had to call it `evidence: 'none'`, which contradicted the 'ai' it had
    // just asserted — and made coverage disagree with attribution.
    it('reports an anonymous AI signal as inferred evidence with an unknown mode', () => {
      const result = tagger('[AI] automated change');
      expect(result.attribution).toBe('ai');
      expect(result.mode).toBe('unknown');
      expect(result.evidence).toBe('inferred');
    });

    it('never infers a mode for non-AI commits', () => {
      const result = tagger('fix: update claude detection pattern'); // mention only
      expect(result.attribution).not.toBe('ai');
      expect(result.mode).toBe('unknown');
      expect(result.evidence).toBe('none');
    });
  });

  describe('declared mode trailer (#61)', () => {
    it('reads AI-Mode as a declaration, beating tool inference', () => {
      const result = tagger(
        'feat: x\n\nCo-Authored-By: Copilot <noreply@github.com>\nAI-Mode: agent'
      );
      // The Copilot trailer would infer autocomplete; the declaration wins
      expect(result.mode).toBe('agent');
      expect(result.evidence).toBe('declared');
      expect(result.attribution).toBe('ai');
      expect(result.sources).toContain('trailer:AI-Mode');
    });

    it('treats AI-Mode: none as a declaration of human authorship', () => {
      const result = tagger('fix: hand written\n\nAI-Mode: none');
      expect(result.attribution).toBe('human');
      expect(result.attribution).not.toBe('ai');
      expect(result.mode).toBe('none');
      expect(result.evidence).toBe('declared');
    });

    it('accepts every documented mode, case-insensitively', () => {
      for (const mode of ['autocomplete', 'assisted', 'agent'] as const) {
        expect(tagger(`feat: x\n\nAI-Mode: ${mode}`).mode).toBe(mode);
      }
      expect(tagger('feat: x\n\nai-mode: AGENT').mode).toBe('agent');
    });

    it('ignores an unrecognized mode value rather than trusting it', () => {
      const result = tagger('feat: x\n\nAI-Mode: wizard');
      expect(result.mode).toBe('unknown');
      expect(result.evidence).toBe('none');
    });
  });

  describe('three-state attribution', () => {
    it('maps explicit and implicit levels to attribution: ai', () => {
      expect(tagger('[AI] automated change').attribution).toBe('ai');
      expect(tagger('feat: copilot suggestions applied').attribution).toBe('ai');
    });

    it('maps mention and none levels to attribution: unknown, never human', () => {
      expect(tagger('fix: update claude detection pattern').attribution).toBe('unknown');
      expect(tagger('regular commit with no AI signal').attribution).toBe('unknown');
    });
  });
});

describe('github.com is not an AI signal by itself (external-repo false positives)', () => {
  const tagger = createAITagger();

  // Found by running evidtrail against commander.js: 2 of its 3 "AI" detections
  // were ordinary humans who co-authored via the GitHub web UI.
  it('does not flag a human co-author on users.noreply.github.com', () => {
    const cases = [
      'Trim description\n\nCo-authored-by: Misha Kaletsky <mmkal@users.noreply.github.com>',
      'Respect negate property\n\nCo-authored-by: bernard-wagner@users.noreply.github.com',
    ];
    for (const message of cases) {
      const result = tagger(message);
      expect(result.attribution).not.toBe('ai');
      expect(result.attribution).toBe('unknown');
    }
  });

  it('still flags AI bots hosted on github.com via the tool-name rule', () => {
    expect(tagger('feat: x\n\nCo-authored-by: copilot[bot] <copilot@github.com>').attribution).toBe('ai');
  });

  it('classifies copilot-swe-agent as an agent, not autocomplete', () => {
    const result = tagger(
      'Bump deps\n\nCo-authored-by: copilot-swe-agent[bot] <198982749+Copilot@users.noreply.github.com>'
    );
    expect(result.attribution).toBe('ai');
    expect(result.mode).toBe('agent');
  });

  it('keeps plain copilot autonomy unknown', () => {
    expect(tagger('feat: generated by copilot').mode).toBe('unknown');
  });
});

describe('an unnamed bot co-author is not an AI signal (external-repo false positives)', () => {
  const tagger = createAITagger();

  // Found by running evidtrail against babel: 47 of its 52 "AI" detections were
  // ordinary PRs co-authored by "Babel Bot", the project's own release and
  // formatting bot. The old `Co-authored-by:.*bot.*` rule read "a bot
  // participated" as "AI wrote this".
  it('does not flag a project automation bot with no tool name', () => {
    const cases = [
      'Add v7.29.8 to CHANGELOG.md\n\nCo-authored-by: Babel Bot <babel-bot@users.noreply.github.com>',
      'fix: something\n\nCo-authored-by: Babel Bot <30521560+liuxingbaoyu@users.noreply.github.com>',
      'chore: reformat\n\nCo-authored-by: some-random-bot <sr@example.com>',
    ];
    for (const message of cases) {
      const result = tagger(message);
      expect(result.attribution).not.toBe('ai');
      expect(result.attribution).toBe('unknown');
    }
  });

  // The name-substring version of the same mistake: `.*bot.*` is unanchored,
  // so any co-author whose name merely contains "bot" was read as AI.
  it('does not flag a human whose name contains "bot"', () => {
    const result = tagger('Fix parser\n\nCo-authored-by: Tim Abbott <tabbott@example.com>');
    expect(result.attribution).not.toBe('ai');
    expect(result.attribution).toBe('unknown');
  });

  // Tool identity establishes involvement, not the mode in which a flexible
  // assistant was used. Only autonomous product identities are precise.
  it('keeps ambiguous trailer-detected autonomy unknown', () => {
    const detected = [
      'feat: x\n\nCo-authored-by: copilot-swe-agent[bot] <198982749+Copilot@users.noreply.github.com>',
      'feat: x\n\nCo-authored-by: Claude <noreply@anthropic.com>',
      'feat: x\n\nCo-authored-by: Cursor <cursor@example.com>',
    ];
    for (const message of detected.slice(1)) {
      const result = tagger(message);
      expect(result.attribution).toBe('ai');
      expect(result.mode).toBe('unknown');
    }
    expect(tagger(detected[0]).mode).toBe('agent');
  });
});

describe('two-axis model (#25)', () => {
  const tagger = createAITagger();

  // The whole point of the refactor: `attribution` is a view, not a second
  // opinion. If anything ever decides it independently, this fails.
  it('always agrees with the projection of its own axes', () => {
    const messages = [
      'feat: plain commit',
      '[AI] anonymous signal',
      'feat: generated by copilot',
      'feat: x\n\nCo-authored-by: Claude <noreply@anthropic.com>',
      'chore: release\n\nAI-Mode: none',
      'feat: y\n\nAI-Mode: agent',
      'fix: update cursor detection pattern',
    ];
    for (const message of messages) {
      const result = tagger(message);
      expect(result.attribution).toBe(projectAttribution(result));
    }
  });

  // `unknown` used to be a fourth kind of attribution. It is now exactly one
  // thing: the absence of evidence. Coverage depends on this holding.
  it('ties attribution unknown to evidence none, in both directions', () => {
    const withoutEvidence = tagger('feat: plain commit');
    expect(withoutEvidence.evidence).toBe('none');
    expect(withoutEvidence.attribution).toBe('unknown');

    const withEvidence = tagger('feat: y\n\nAI-Mode: assisted');
    expect(withEvidence.evidence).not.toBe('none');
    expect(withEvidence.attribution).not.toBe('unknown');
  });

  it('reads AI-Mode: none as a human declaration, not as absent evidence', () => {
    const result = tagger('chore: hand-written\n\nAI-Mode: none');
    expect(result.mode).toBe('none');
    expect(result.evidence).toBe('declared');
    expect(result.attribution).toBe('human');
  });

  it('never marks a message-tagged commit as automated', () => {
    // Automation is orthogonal: it is set at collect time from commit
    // structure and authorship, never from message heuristics.
    expect(tagger('Merge branch main').automated).toBe(false);
    expect(tagger('feat: y\n\nAI-Mode: agent').automated).toBe(false);
  });
});
